### ISSUE TITLE
Awesome write-up on modules

### ISSUE THREAD

**Issue by mparisi76** [jdx/ng-modules#1]
I too had converted my simple(ish) angular app to use requirejs and what a friggin headache. I love your solution and I've not used gulp before, but i've decided to try it out. I have a strange thing happening and I thought maybe you could provide insight. After I run "gulp js" and the app.js file is output, every time I try opening it in sublime 2, it crashes sublime. Any thoughts on why this might happen? (I realize it's probably more of a sublime thing but thought I would throw it out there anyway..)

Thanks in advance.

**Comment by jdx** [comment]
that's something with your editor, probably related to it being a giant, single line file with a huge sourcemap on it

**Comment by mparisi76** [comment]
Yea, I figured. Thanks. Your example is very basic. What would be the best place to put a views folder? In src or at the top level?

**Comment by jdx** [comment]
at the top level, `src` is for code

**Comment by mparisi76** [comment]
That's where I put it, just wanted to make sure. Thanks.
